name: Lint Code

on:
  push:
    branches:
      - main # veya izlemek istediğiniz diğer branşları ekleyin

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Projenizin Node.js sürümüne uygun olarak güncelleyin

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
